package com.pangility.schwab.api.client.accountsandtrading.model.order;

public enum Status {
  AWAITING_PARENT_ORDER,
  AWAITING_CONDITION,
  AWAITING_MANUAL_REVIEW,
  ACCEPTED,
  AWAITING_UR_OUT,
  PENDING_ACTIVATION,
  QUEUED,
  WORKING,
  REJECTED,
  PENDING_CANCEL,
  CANCELED,
  PENDING_REPLACE,
  REPLACED,
  FILLED,
  EXPIRED
}
